# This formula is auto-generated by the release workflow.
# Latest stable version will be pushed here after each release.
class Codewhale < Formula
  desc "Terminal-native coding agent for any model — open models first"
  homepage "https://github.com/tanuki-cat/CodeWhale"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-macos-arm64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      resource "tui" do
        url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-tui-macos-arm64", using: :nounzip
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      end
    else
      url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-macos-x64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      resource "tui" do
        url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-tui-macos-x64", using: :nounzip
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-linux-arm64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      resource "tui" do
        url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-tui-linux-arm64", using: :nounzip
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      end
    else
      url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-linux-x64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      resource "tui" do
        url "https://github.com/tanuki-cat/CodeWhale/releases/download/v0.0.0/codewhale-tui-linux-x64", using: :nounzip
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      end
    end
  end

  def install
    bin.install Dir["*"].first => "codewhale"
    resource("tui").stage { bin.install Dir["*"].first => "codewhale-tui" }
  end

  test do
    system "#{bin}/codewhale", "--version"
  end
end
